import { Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import type {
  AlertDetail,
  AlertEvaluationResult,
  AlertEvidence,
  AlertSeverity,
  AlertStatus,
  AlertSummary,
  Paginated,
  PeriodType,
} from '@sip/shared-types';
import { PrismaService } from '../prisma/prisma.service';
import { ApiException } from '../common/errors/api-exception';
import { AuditService } from '../audit/audit.service';
import { AnalyticsService } from '../analytics/analytics.service';
import { DataQualityService } from '../data-quality/data-quality.service';
import { evaluateAlertRule, type AlertRuleType, type RuleFacts } from './alert-rules';
import type { ListAlertsDto, UpdateAlertStatusDto } from './alerts.dto';

const ALERT_SELECT = {
  id: true,
  severity: true,
  status: true,
  title: true,
  description: true,
  periodType: true,
  periodStart: true,
  evidence: true,
  createdAt: true,
  updatedAt: true,
  metricId: true,
  metric: { select: { code: true, name: true } },
  alertRule: { select: { code: true, name: true, type: true } },
} as const;

type AlertRow = Prisma.AlertGetPayload<{ select: typeof ALERT_SELECT }>;

/**
 * The alerts engine (plan §27).
 *
 * Rules come from the industry pack the organization installed, or from the
 * tenant; the engine evaluates them against one period and writes an alert when
 * one fires, carrying the figures that made it fire. Nothing is generated by a
 * model (ADR-0005).
 */
@Injectable()
export class AlertsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
    private readonly dataQuality: DataQualityService,
    private readonly analytics: AnalyticsService,
  ) {}

  async list(organizationId: string, query: ListAlertsDto): Promise<Paginated<AlertSummary>> {
    const where: Prisma.AlertWhereInput = {
      organizationId,
      ...(query.status ? { status: query.status } : {}),
      ...(query.severity ? { severity: query.severity } : {}),
      ...(query.metricId ? { metricId: query.metricId } : {}),
    };

    const [rows, total] = await Promise.all([
      this.prisma.alert.findMany({
        where,
        orderBy: [{ status: 'asc' }, { severity: 'desc' }, { createdAt: 'desc' }],
        skip: (query.page - 1) * query.pageSize,
        take: query.pageSize,
        select: ALERT_SELECT,
      }),
      this.prisma.alert.count({ where }),
    ]);

    return {
      items: rows.map(toSummary),
      page: query.page,
      pageSize: query.pageSize,
      total,
    };
  }

  async detail(organizationId: string, id: string): Promise<AlertDetail> {
    const alert = await this.prisma.alert.findFirst({
      where: { id, organizationId },
      select: {
        ...ALERT_SELECT,
        events: {
          orderBy: { createdAt: 'asc' },
          select: {
            id: true,
            fromStatus: true,
            toStatus: true,
            note: true,
            createdAt: true,
            actorId: true,
          },
        },
      },
    });

    if (!alert) {
      throw ApiException.notFound('Alert');
    }

    const actorIds = [...new Set(alert.events.map((event) => event.actorId).filter(Boolean))];
    const actors = await this.prisma.user.findMany({
      where: { id: { in: actorIds as string[] } },
      select: { id: true, fullName: true },
    });
    const names = new Map(actors.map((actor) => [actor.id, actor.fullName]));

    return {
      ...toSummary(alert),
      events: alert.events.map((event) => ({
        id: event.id,
        fromStatus: event.fromStatus,
        toStatus: event.toStatus,
        note: event.note,
        actorName: event.actorId ? (names.get(event.actorId) ?? null) : null,
        createdAt: event.createdAt.toISOString(),
      })),
    };
  }

  /**
   * Moves an alert through its workflow (plan §27).
   *
   * Every transition is recorded with who made it and why, so an alert that was
   * dismissed can be asked about later.
   */
  async setStatus(
    organizationId: string,
    id: string,
    actorId: string,
    dto: UpdateAlertStatusDto,
    ipAddress?: string,
  ): Promise<AlertDetail> {
    const alert = await this.prisma.alert.findFirst({
      where: { id, organizationId },
      select: { id: true, status: true, title: true },
    });

    if (!alert) {
      throw ApiException.notFound('Alert');
    }

    if (alert.status === dto.status) {
      return this.detail(organizationId, id);
    }

    if (alert.status === 'RESOLVED' || alert.status === 'DISMISSED') {
      throw ApiException.conflict(
        `This alert is already ${alert.status.toLowerCase()} and cannot be changed again.`,
      );
    }

    await this.prisma.$transaction([
      this.prisma.alert.update({ where: { id }, data: { status: dto.status } }),
      this.prisma.alertEvent.create({
        data: {
          alertId: id,
          actorId,
          fromStatus: alert.status,
          toStatus: dto.status,
          note: dto.note ?? null,
        },
      }),
    ]);

    await this.audit.record({
      actorId,
      organizationId,
      action: 'alert.status_changed',
      entityType: 'alert',
      entityId: id,
      before: { status: alert.status },
      after: { status: dto.status, note: dto.note ?? null },
      ipAddress,
    });

    return this.detail(organizationId, id);
  }

  /**
   * Evaluates every active rule against a period.
   *
   * Idempotent: a rule that still fires for a period it already raised leaves the
   * existing alert alone, and one that no longer fires resolves it. Running the
   * engine twice therefore changes nothing, which is what makes it safe to run
   * after every import.
   */
  async evaluate(
    organizationId: string,
    period: { periodType: PeriodType; periodStart: Date },
    actorId?: string,
  ): Promise<AlertEvaluationResult> {
    const rules = await this.prisma.alertRule.findMany({
      where: { organizationId, isActive: true },
      select: {
        id: true,
        code: true,
        name: true,
        type: true,
        severity: true,
        definition: true,
        metricId: true,
        metric: {
          select: {
            id: true,
            code: true,
            name: true,
            unit: true,
            direction: true,
            thresholds: {
              select: { warningValue: true, criticalValue: true, isRelativeToTarget: true },
              take: 1,
            },
          },
        },
      },
    });

    const result: AlertEvaluationResult = {
      created: 0,
      resolved: 0,
      unchanged: 0,
      rulesEvaluated: rules.length,
    };

    if (rules.length === 0) {
      return result;
    }

    const context = await this.factsFor(organizationId, period);

    for (const rule of rules) {
      const facts = rule.metric ? context.metrics.get(rule.metric.id) : null;

      const outcome = evaluateAlertRule(
        rule.type as AlertRuleType,
        (rule.definition ?? {}) as Record<string, unknown>,
        rule.severity,
        {
          metricName: rule.metric?.name ?? rule.name,
          metricCode: rule.metric?.code ?? rule.code,
          unit: rule.metric?.unit ?? 'NUMBER',
          value: facts?.value ?? null,
          previousValue: facts?.previousValue ?? null,
          changePct: facts?.changePct ?? null,
          target: facts?.target ?? null,
          warningValue: rule.metric?.thresholds[0]?.warningValue
            ? Number(rule.metric.thresholds[0].warningValue)
            : null,
          criticalValue: rule.metric?.thresholds[0]?.criticalValue
            ? Number(rule.metric.thresholds[0].criticalValue)
            : null,
          isRelativeToTarget: rule.metric?.thresholds[0]?.isRelativeToTarget ?? false,
          direction: rule.metric?.direction ?? 'HIGHER_IS_BETTER',
          daysSinceImport: context.daysSinceImport,
          dataQualityScore: context.dataQualityScore,
        } satisfies RuleFacts,
      );

      const existing = await this.prisma.alert.findFirst({
        where: {
          organizationId,
          alertRuleId: rule.id,
          metricId: rule.metricId,
          periodType: period.periodType,
          periodStart: period.periodStart,
        },
        select: { id: true, status: true },
      });

      if (outcome.fires) {
        if (existing) {
          // The condition still holds, so the alert keeps its identity and anything
          // a person has done with it — but its figures are refreshed, because an
          // alert showing last week's numbers for a corrected month is a lie with a
          // timestamp. An alert someone has already closed is left frozen.
          if (existing.status === 'OPEN' || existing.status === 'ACKNOWLEDGED') {
            await this.prisma.alert.update({
              where: { id: existing.id },
              data: {
                severity: outcome.severity ?? rule.severity,
                title: outcome.title ?? 'Alert',
                description: outcome.description ?? '',
                evidence: (outcome.evidence ?? {
                  statement: '',
                  figures: [],
                }) as unknown as Prisma.InputJsonValue,
              },
            });
          }

          result.unchanged += 1;
          continue;
        }

        await this.raise(organizationId, rule, period, outcome);
        result.created += 1;
        continue;
      }

      // The condition has passed. An open alert is resolved by the engine itself,
      // so a dashboard never shows a problem that has already gone away; one a
      // person dismissed or resolved is left exactly as they left it.
      if (existing && (existing.status === 'OPEN' || existing.status === 'ACKNOWLEDGED')) {
        await this.prisma.$transaction([
          this.prisma.alert.update({ where: { id: existing.id }, data: { status: 'RESOLVED' } }),
          this.prisma.alertEvent.create({
            data: {
              alertId: existing.id,
              actorId: actorId ?? null,
              fromStatus: existing.status,
              toStatus: 'RESOLVED',
              note: 'The condition that raised this alert no longer holds.',
            },
          }),
        ]);

        result.resolved += 1;
      }
    }

    return result;
  }

  private async raise(
    organizationId: string,
    rule: { id: string; metricId: string | null; severity: AlertSeverity },
    period: { periodType: PeriodType; periodStart: Date },
    outcome: {
      severity?: AlertSeverity;
      title?: string;
      description?: string;
      evidence?: AlertEvidence;
    },
  ): Promise<void> {
    const alert = await this.prisma.alert.create({
      data: {
        organizationId,
        alertRuleId: rule.id,
        metricId: rule.metricId,
        severity: outcome.severity ?? rule.severity,
        status: 'OPEN',
        title: outcome.title ?? 'Alert',
        description: outcome.description ?? '',
        periodType: period.periodType,
        periodStart: period.periodStart,
        evidence: (outcome.evidence ?? {
          statement: '',
          figures: [],
        }) as unknown as Prisma.InputJsonValue,
      },
      select: { id: true },
    });

    await this.prisma.alertEvent.create({
      data: { alertId: alert.id, toStatus: 'OPEN', note: 'Raised by the alerts engine.' },
    });
  }

  /**
   * The figures every rule reads for this period.
   *
   * Read through the analytics engine, so a rule sees exactly what the dashboard
   * and the metric page see — branch roll-ups included, formulas recomputed from
   * their inputs. A rule that disagreed with the screen it points at would be
   * worse than no rule.
   */
  private async factsFor(
    organizationId: string,
    period: { periodType: PeriodType; periodStart: Date },
  ): Promise<{
    metrics: Map<
      string,
      {
        value: number | null;
        previousValue: number | null;
        changePct: number | null;
        target: number | null;
      }
    >;
    daysSinceImport: number | null;
    dataQualityScore: number | null;
  }> {
    const [context, quality] = await Promise.all([
      this.analytics.contextForPeriod(organizationId, period),
      this.dataQuality.report(organizationId),
    ]);

    const metrics = new Map<
      string,
      {
        value: number | null;
        previousValue: number | null;
        changePct: number | null;
        target: number | null;
      }
    >();

    for (const metric of context.metrics) {
      const summary = this.analytics.summarise(context, metric);

      metrics.set(metric.id, {
        value: summary.current === null ? null : Number(summary.current),
        previousValue: summary.previous === null ? null : Number(summary.previous),
        changePct: summary.changePct === null ? null : Number(summary.changePct),
        target: summary.target === null ? null : Number(summary.target),
      });
    }

    return {
      metrics,
      daysSinceImport: quality.daysSinceLastImport,
      dataQualityScore: quality.lastUpdatedAt === null ? null : quality.overallScore,
    };
  }
}

function toSummary(alert: AlertRow): AlertSummary {
  // The column is JSON, so what comes back is whatever was written; it is read
  // defensively rather than trusted to still match the type.
  const evidence = (alert.evidence ?? {}) as unknown as Partial<AlertEvidence>;

  return {
    id: alert.id,
    ruleCode: alert.alertRule?.code ?? null,
    ruleName: alert.alertRule?.name ?? null,
    ruleType: alert.alertRule?.type ?? null,
    metricId: alert.metricId,
    metricCode: alert.metric?.code ?? null,
    metricName: alert.metric?.name ?? null,
    severity: alert.severity,
    status: alert.status as AlertStatus,
    title: alert.title,
    description: alert.description,
    periodType: alert.periodType,
    periodStart: alert.periodStart ? alert.periodStart.toISOString().slice(0, 10) : null,
    evidence: { statement: evidence.statement ?? '', figures: evidence.figures ?? [] },
    createdAt: alert.createdAt.toISOString(),
    updatedAt: alert.updatedAt.toISOString(),
  };
}
