import type { INestApplication } from '@nestjs/common';
import request from 'supertest';
import type { PrismaService } from '../src/prisma/prisma.service';
import { createOrganization, createUser } from './helpers/fixtures';
import { cleanupFixtures, createTestApp, TEST_PASSWORD, unique } from './helpers/test-app';

/**
 * Sprint 7 gate (plan §42): every generated alert and insight can explain why it
 * was created, and nothing is generated by a model.
 *
 * The organization is built with figures chosen so each engine has an unambiguous
 * right answer: revenue misses its target, the no-show rate crosses its critical
 * line, and volume rises while revenue per patient falls.
 */
describe('Health, alerts and insights (e2e)', () => {
  let app: INestApplication;
  let prisma: PrismaService;

  const organizationIds: string[] = [];
  const userIds: string[] = [];

  let organization: { id: string };
  let other: { id: string };
  let admin: { email: string };
  let viewer: { email: string };
  let otherAdmin: { email: string };
  let branch: string;

  const metricIds: Record<string, string> = {};
  let modelId: string;
  let noShowRuleId: string;
  let insightRuleId: string;

  const JANUARY = new Date('2026-01-01T00:00:00.000Z');
  const FEBRUARY = new Date('2026-02-01T00:00:00.000Z');

  beforeAll(async () => {
    ({ app, prisma } = await createTestApp());

    organization = await createOrganization(prisma, { name: 'Health Co' });
    other = await createOrganization(prisma, { name: 'Other Health Co' });
    organizationIds.push(organization.id, other.id);

    admin = await createUser(prisma, {
      memberships: [
        { organizationId: organization.id, role: 'ORGANIZATION_ADMIN', isDefault: true },
      ],
    });
    viewer = await createUser(prisma, {
      memberships: [{ organizationId: organization.id, role: 'VIEWER', isDefault: true }],
    });
    otherAdmin = await createUser(prisma, {
      memberships: [{ organizationId: other.id, role: 'ORGANIZATION_ADMIN', isDefault: true }],
    });

    const users = await prisma.user.findMany({
      where: { email: { in: [admin.email, viewer.email, otherAdmin.email] } },
      select: { id: true },
    });
    userIds.push(...users.map((user) => user.id));

    const suffix = unique('h').split('-')[1];
    const created = await prisma.branch.create({
      data: { organizationId: organization.id, code: `main_${suffix}`, name: 'Main Clinic' },
    });
    branch = created.id;

    const agent = await signIn(admin.email);

    for (const definition of [
      { code: 'revenue', name: 'Revenue', unit: 'CURRENCY', direction: 'HIGHER_IS_BETTER' },
      { code: 'patients', name: 'Patients', unit: 'COUNT', direction: 'HIGHER_IS_BETTER' },
      {
        code: 'no_show_rate',
        name: 'No-Show Rate',
        unit: 'PERCENTAGE',
        direction: 'LOWER_IS_BETTER',
        aggregationType: 'AVERAGE',
      },
      {
        code: 'revenue_per_patient',
        name: 'Revenue per Patient',
        unit: 'CURRENCY',
        direction: 'HIGHER_IS_BETTER',
        aggregationType: 'FORMULA',
        formula: 'revenue / patients',
      },
    ]) {
      const response = await agent
        .post('/api/metrics')
        .send({
          frequency: 'MONTHLY',
          category: 'Clinical',
          aggregationType: 'SUM',
          ...definition,
        })
        .expect(201);

      metricIds[definition.code] = response.body.id;
    }

    // January: the baseline. February: revenue down, volume up, no-shows worse.
    await writeValues(JANUARY, { revenue: 1000, patients: 100, no_show_rate: 5 });
    await writeValues(FEBRUARY, { revenue: 900, patients: 120, no_show_rate: 12 });

    await agent.post('/api/metrics/recalculate').expect(200);

    // Targets and thresholds are what the engines judge against.
    await agent
      .put(`/api/metrics/${metricIds.revenue}/target`)
      .send({ period: '2026-02', targetValue: '1200' })
      .expect(200);
    await agent
      .put(`/api/metrics/${metricIds.no_show_rate}/target`)
      .send({ period: '2026-02', targetValue: '6' })
      .expect(200);
    await agent
      .put(`/api/metrics/${metricIds.no_show_rate}/threshold`)
      .send({ warningValue: '8', criticalValue: '10' })
      .expect(200);
    await agent
      .put(`/api/metrics/${metricIds.patients}/target`)
      .send({ period: '2026-02', targetValue: '110' })
      .expect(200);

    // A health model weighing the three reported metrics.
    const model = await prisma.healthModel.create({
      data: {
        organizationId: organization.id,
        name: 'Clinic Health Model',
        categories: {
          create: [
            {
              code: 'financial',
              name: 'Financial',
              weight: 60,
              displayOrder: 0,
              weights: { create: [{ metricId: metricIds.revenue, weight: 100 }] },
            },
            {
              code: 'operations',
              name: 'Operations',
              weight: 40,
              displayOrder: 1,
              weights: {
                create: [
                  { metricId: metricIds.no_show_rate, weight: 50 },
                  { metricId: metricIds.patients, weight: 50 },
                ],
              },
            },
          ],
        },
      },
      select: { id: true },
    });
    modelId = model.id;

    const noShowRule = await prisma.alertRule.create({
      data: {
        organizationId: organization.id,
        code: 'no_show_above',
        name: 'No-show rate above threshold',
        metricId: metricIds.no_show_rate,
        type: 'METRIC_ABOVE_THRESHOLD',
        severity: 'WARNING',
        definition: { usesConfiguredThreshold: true },
      },
      select: { id: true },
    });
    noShowRuleId = noShowRule.id;

    await prisma.alertRule.create({
      data: {
        organizationId: organization.id,
        code: 'revenue_target_missed',
        name: 'Revenue target missed',
        metricId: metricIds.revenue,
        type: 'TARGET_MISSED',
        severity: 'HIGH',
        definition: { tolerancePct: 5 },
      },
      select: { id: true },
    });

    const insightRule = await prisma.insightRule.create({
      data: {
        organizationId: organization.id,
        code: 'volume_up_monetization_down',
        name: 'Volume up, monetization down',
        definition: {
          severity: 'WARNING',
          category: 'Financial',
          conditions: [
            { metric: 'patients', measure: 'CHANGE_PCT', operator: 'GT', value: 0 },
            { metric: 'revenue_per_patient', measure: 'CHANGE_PCT', operator: 'LT', value: 0 },
          ],
          narrative: 'Patient volume is increasing but monetization per patient is declining.',
          evidence: ['patients', 'revenue_per_patient', 'revenue'],
        },
      },
      select: { id: true },
    });
    insightRuleId = insightRule.id;
  });

  afterAll(async () => {
    await prisma.alertEvent.deleteMany({
      where: { alert: { organizationId: { in: organizationIds } } },
    });
    await prisma.alert.deleteMany({ where: { organizationId: { in: organizationIds } } });
    await prisma.alertRule.deleteMany({ where: { organizationId: { in: organizationIds } } });
    await prisma.insightEvidence.deleteMany({
      where: { insight: { organizationId: { in: organizationIds } } },
    });
    await prisma.insight.deleteMany({ where: { organizationId: { in: organizationIds } } });
    await prisma.insightRule.deleteMany({ where: { organizationId: { in: organizationIds } } });
    await prisma.healthScore.deleteMany({ where: { organizationId: { in: organizationIds } } });
    await prisma.healthModel.deleteMany({ where: { organizationId: { in: organizationIds } } });
    await prisma.metricValue.deleteMany({ where: { organizationId: { in: organizationIds } } });
    await prisma.metricTarget.deleteMany({ where: { organizationId: { in: organizationIds } } });
    await prisma.metricThreshold.deleteMany({ where: { organizationId: { in: organizationIds } } });
    await prisma.metric.deleteMany({ where: { organizationId: { in: organizationIds } } });
    await prisma.branch.deleteMany({ where: { organizationId: { in: organizationIds } } });
    await cleanupFixtures(prisma, { organizationIds, userIds });
    await app?.close();
  });

  async function signIn(email: string) {
    const agent = request.agent(app.getHttpServer());
    await agent.post('/api/auth/login').send({ email, password: TEST_PASSWORD }).expect(200);
    return agent;
  }

  async function writeValues(periodStart: Date, values: Record<string, number>) {
    const periodEnd = new Date(
      Date.UTC(periodStart.getUTCFullYear(), periodStart.getUTCMonth() + 1, 0),
    );

    for (const [code, value] of Object.entries(values)) {
      await prisma.metricValue.create({
        data: {
          organizationId: organization.id,
          metricId: metricIds[code],
          branchId: branch,
          periodType: 'MONTH',
          periodStart,
          periodEnd,
          value,
          sourceType: 'MANUAL',
        },
      });
    }
  }

  describe('the health score', () => {
    it('scores the period and explains itself metric by metric', async () => {
      const agent = await signIn(admin.email);

      const run = await agent.post('/api/analysis/run').expect(200);
      expect(run.body[0].health.periodsScored).toBe(1);

      const response = await agent.get('/api/health/current').expect(200);
      const current = response.body.current;

      expect(current.periodStart).toBe('2026-02-01');
      expect(current.overallScore).toBeGreaterThan(0);
      expect(current.overallScore).toBeLessThan(100);
      expect(response.body.bands).toHaveLength(4);

      const financial = current.categories.find(
        (category: { code: string }) => category.code === 'financial',
      );
      const revenue = financial.metrics[0];

      // 900 against a target of 1200 is three quarters of the way there, and the
      // breakdown says exactly that.
      expect(revenue.code).toBe('revenue');
      expect(revenue.value).toBe('900');
      expect(revenue.target).toBe('1200');
      expect(revenue.score).toBe(75);
      expect(revenue.basis).toBe('TARGET');
      expect(financial.score).toBe(75);
    });

    it('weights the categories as configured', async () => {
      const agent = await signIn(admin.email);
      const response = await agent.get('/api/health/current').expect(200);

      const categories = Object.fromEntries(
        response.body.current.categories.map((category: { code: string; score: number }) => [
          category.code,
          category.score,
        ]),
      );

      // Financial 60% and Operations 40%, so the overall is exactly their blend.
      const expected = categories.financial * 0.6 + categories.operations * 0.4;

      expect(response.body.current.overallScore).toBeCloseTo(expected, 1);
    });

    it('never scores a metric it has no benchmark for', async () => {
      const agent = await signIn(admin.email);
      const response = await agent.get('/api/health/current').expect(200);

      const operations = response.body.current.categories.find(
        (category: { code: string }) => category.code === 'operations',
      );

      for (const metric of operations.metrics) {
        if (metric.score === null) {
          expect(['NO_VALUE', 'NO_BENCHMARK', 'INFORMATIONAL']).toContain(metric.basis);
        } else {
          expect(metric.target ?? metric.basis).toBeTruthy();
        }
      }
    });

    it('keeps a history that a chart can read', async () => {
      const agent = await signIn(admin.email);
      await agent.post('/api/health/recalculate').expect(201);

      const history = await agent.get('/api/health/history').expect(200);

      expect(history.body.length).toBeGreaterThanOrEqual(2);
      expect(history.body[0].periodStart < history.body[1].periodStart).toBe(true);
      expect(history.body.at(-1)).toMatchObject({ periodStart: '2026-02-01' });
    });

    it('rescoring the same period replaces the score rather than adding one', async () => {
      const agent = await signIn(admin.email);

      await agent.post('/api/health/recalculate').expect(201);
      await agent.post('/api/health/recalculate').expect(201);

      const scores = await prisma.healthScore.count({
        where: { organizationId: organization.id, healthModelId: modelId, periodStart: FEBRUARY },
      });

      expect(scores).toBe(1);
    });
  });

  describe('alerts', () => {
    it('raises an alert only when a rule fires, and says why', async () => {
      const agent = await signIn(admin.email);
      await agent.post('/api/analysis/run').expect(200);

      const response = await agent.get('/api/alerts?status=OPEN').expect(200);
      const alerts: Array<{
        ruleCode: string;
        severity: string;
        evidence: { statement: string; figures: unknown[] };
      }> = response.body.items;

      const noShow = alerts.find((alert) => alert.ruleCode === 'no_show_above');
      const revenue = alerts.find((alert) => alert.ruleCode === 'revenue_target_missed');

      expect(noShow).toBeDefined();
      expect(revenue).toBeDefined();

      // 12 is past the critical line of 10, so the severity is raised beyond the
      // rule's configured WARNING.
      expect(noShow?.severity).toBe('CRITICAL');
      expect(noShow?.evidence.statement).toContain('12');
      expect(noShow?.evidence.figures.length).toBeGreaterThan(1);

      expect(revenue?.severity).toBe('HIGH');
      expect(revenue?.evidence.statement).toContain('1200');
    });

    it('every alert carries evidence — the acceptance criterion', async () => {
      const agent = await signIn(admin.email);
      const response = await agent.get('/api/alerts').expect(200);

      for (const alert of response.body.items) {
        expect(alert.evidence.statement.length).toBeGreaterThan(5);
        expect(alert.evidence.figures.length).toBeGreaterThan(0);
        expect(alert.description.length).toBeGreaterThan(10);
        expect(alert.periodStart).toBe('2026-02-01');
      }
    });

    it('does not raise the same alert twice for the same period', async () => {
      const agent = await signIn(admin.email);

      const first = await agent.post('/api/analysis/run').expect(200);
      const second = await agent.post('/api/analysis/run').expect(200);

      expect(second.body[0].alerts.created).toBe(0);
      expect(second.body[0].alerts.unchanged).toBeGreaterThanOrEqual(
        first.body[0].alerts.unchanged,
      );

      const count = await prisma.alert.count({
        where: { organizationId: organization.id, alertRuleId: noShowRuleId },
      });

      expect(count).toBe(1);
    });

    it('records every status change with who made it and why', async () => {
      const agent = await signIn(admin.email);
      const list = await agent.get('/api/alerts?status=OPEN').expect(200);
      const target = list.body.items.find(
        (alert: { ruleCode: string }) => alert.ruleCode === 'revenue_target_missed',
      );

      const acknowledged = await agent
        .patch(`/api/alerts/${target.id}/status`)
        .send({ status: 'ACKNOWLEDGED', note: 'Finance is reviewing the month.' })
        .expect(200);

      expect(acknowledged.body.status).toBe('ACKNOWLEDGED');
      expect(acknowledged.body.events.at(-1)).toMatchObject({
        fromStatus: 'OPEN',
        toStatus: 'ACKNOWLEDGED',
        note: 'Finance is reviewing the month.',
      });
      expect(acknowledged.body.events.at(-1).actorName).toBeTruthy();

      const resolved = await agent
        .patch(`/api/alerts/${target.id}/status`)
        .send({ status: 'RESOLVED' })
        .expect(200);

      expect(resolved.body.events).toHaveLength(3);

      // A closed alert stays closed: reopening it would erase the decision.
      const refused = await agent
        .patch(`/api/alerts/${target.id}/status`)
        .send({ status: 'OPEN' })
        .expect(409);

      expect(refused.body.code).toBe('CONFLICT');
    });

    it('resolves an alert by itself once the condition passes', async () => {
      const agent = await signIn(admin.email);

      const before = await prisma.alert.findFirstOrThrow({
        where: { organizationId: organization.id, alertRuleId: noShowRuleId },
        select: { id: true, status: true },
      });
      expect(['OPEN', 'ACKNOWLEDGED']).toContain(before.status);

      // The month is corrected: the no-show rate was actually well inside its limits.
      await prisma.metricValue.updateMany({
        where: {
          organizationId: organization.id,
          metricId: metricIds.no_show_rate,
          periodStart: FEBRUARY,
        },
        data: { value: 4 },
      });

      const run = await agent.post('/api/analysis/run').expect(200);
      expect(run.body[0].alerts.resolved).toBeGreaterThanOrEqual(1);

      const after = await prisma.alert.findUniqueOrThrow({
        where: { id: before.id },
        select: { status: true, events: { orderBy: { createdAt: 'desc' }, take: 1 } },
      });

      expect(after.status).toBe('RESOLVED');
      expect(after.events[0].note).toContain('no longer holds');

      // Put the month back for the tests that follow.
      await prisma.metricValue.updateMany({
        where: {
          organizationId: organization.id,
          metricId: metricIds.no_show_rate,
          periodStart: FEBRUARY,
        },
        data: { value: 12 },
      });
    });

    it('refreshes the figures on a live alert when the month is corrected', async () => {
      const agent = await signIn(admin.email);

      await prisma.metricValue.updateMany({
        where: {
          organizationId: organization.id,
          metricId: metricIds.revenue,
          periodStart: FEBRUARY,
        },
        data: { value: 800 },
      });
      await agent.post('/api/metrics/recalculate').expect(200);
      await agent.post('/api/analysis/run').expect(200);

      const alerts = await agent.get('/api/alerts').expect(200);
      const revenueAlert = alerts.body.items.find(
        (alert: { ruleCode: string; status: string }) =>
          alert.ruleCode === 'revenue_target_missed' && alert.status !== 'RESOLVED',
      );

      if (revenueAlert) {
        // An alert showing last week's numbers for a corrected month would be a lie
        // with a timestamp.
        expect(revenueAlert.evidence.statement).toContain('800');
      }

      await prisma.metricValue.updateMany({
        where: {
          organizationId: organization.id,
          metricId: metricIds.revenue,
          periodStart: FEBRUARY,
        },
        data: { value: 900 },
      });
      await agent.post('/api/metrics/recalculate').expect(200);
    });

    it('lets a viewer read alerts but not decide on them', async () => {
      const reader = await signIn(viewer.email);
      const list = await reader.get('/api/alerts').expect(200);

      await reader
        .patch(`/api/alerts/${list.body.items[0].id}/status`)
        .send({ status: 'DISMISSED' })
        .expect(403);
    });
  });

  describe('insights', () => {
    it('creates an insight only when every condition holds, with evidence for each', async () => {
      const agent = await signIn(admin.email);
      await agent.post('/api/analysis/run').expect(200);

      const response = await agent.get('/api/insights').expect(200);
      const insight = response.body.items.find(
        (entry: { ruleCode: string }) => entry.ruleCode === 'volume_up_monetization_down',
      );

      expect(insight).toBeDefined();
      expect(insight.narrative).toContain('monetization per patient is declining');
      expect(insight.periodStart).toBe('2026-02-01');

      // Patients 100 → 120 (+20%), revenue per patient 10 → 7.5 (-25%).
      const evidence = Object.fromEntries(
        insight.evidence.map((item: { label: string; changePct: string | null }) => [
          item.label,
          item.changePct,
        ]),
      );

      expect(Number(evidence.Patients)).toBeCloseTo(20, 1);
      expect(Number(evidence['Revenue per Patient'])).toBeCloseTo(-25, 1);
      expect(insight.evidence).toHaveLength(3);
    });

    it('every insight carries evidence — the acceptance criterion', async () => {
      const agent = await signIn(admin.email);
      const response = await agent.get('/api/insights').expect(200);

      expect(response.body.items.length).toBeGreaterThan(0);

      for (const insight of response.body.items) {
        expect(insight.evidence.length).toBeGreaterThan(0);
        expect(insight.narrative.length).toBeGreaterThan(20);

        // Each condition the rule tested is recorded against the figure it read.
        const conditions = insight.evidence.filter(
          (item: { detail: Record<string, unknown> | null }) => item.detail !== null,
        );
        expect(conditions.length).toBeGreaterThan(0);
        expect(conditions[0].detail).toHaveProperty('measure');
        expect(conditions[0].detail).toHaveProperty('threshold');
      }
    });

    it('does not write the same insight twice for a period', async () => {
      const agent = await signIn(admin.email);
      await agent.post('/api/analysis/run').expect(200);

      const count = await prisma.insight.count({
        where: { organizationId: organization.id, insightRuleId: insightRuleId },
      });

      expect(count).toBe(1);
    });

    it('does not fire when a condition stops holding', async () => {
      const agent = await signIn(admin.email);

      // January is the first period, so there is no change to read: the rule cannot
      // assert anything about it.
      const before = await prisma.insight.count({ where: { organizationId: organization.id } });

      await prisma.insight.deleteMany({
        where: { organizationId: organization.id, periodStart: JANUARY },
      });

      const runs = await agent.post('/api/analysis/run').expect(200);

      expect(runs.body[0].period).toBe('2026-02-01');
      expect(before).toBeGreaterThan(0);

      const january = await prisma.insight.count({
        where: { organizationId: organization.id, periodStart: JANUARY },
      });
      expect(january).toBe(0);
    });

    it('reads one insight in full', async () => {
      const agent = await signIn(admin.email);
      const list = await agent.get('/api/insights').expect(200);

      const detail = await agent.get(`/api/insights/${list.body.items[0].id}`).expect(200);

      expect(detail.body.id).toBe(list.body.items[0].id);
      expect(detail.body.evidence.length).toBeGreaterThan(0);
    });
  });

  describe('organization isolation', () => {
    it('shows nothing from another organization', async () => {
      const stranger = await signIn(otherAdmin.email);

      const alerts = await stranger.get('/api/alerts').expect(200);
      const insights = await stranger.get('/api/insights').expect(200);
      const health = await stranger.get('/api/health/current').expect(200);

      expect(alerts.body.items).toEqual([]);
      expect(insights.body.items).toEqual([]);
      expect(health.body.current).toBeNull();
    });

    it('404s on another organization’s alert and insight', async () => {
      const agent = await signIn(admin.email);
      const stranger = await signIn(otherAdmin.email);

      const alerts = await agent.get('/api/alerts').expect(200);
      const insights = await agent.get('/api/insights').expect(200);

      await stranger.get(`/api/alerts/${alerts.body.items[0].id}`).expect(404);
      await stranger
        .patch(`/api/alerts/${alerts.body.items[0].id}/status`)
        .send({ status: 'DISMISSED' })
        .expect(404);
      await stranger.get(`/api/insights/${insights.body.items[0].id}`).expect(404);
    });

    it('generates nothing for an organization with no rules or model', async () => {
      const stranger = await signIn(otherAdmin.email);

      const run = await stranger.post('/api/analysis/run').expect(200);

      expect(run.body).toEqual([]);
    });

    it('refuses an unauthenticated caller', async () => {
      await request(app.getHttpServer()).get('/api/alerts').expect(401);
      await request(app.getHttpServer()).get('/api/insights').expect(401);
      await request(app.getHttpServer()).get('/api/health/current').expect(401);
    });

    it('leaves the service liveness probe public and untouched', async () => {
      // Organizational health shares the /health prefix with it; the probe still
      // answers without a session and reports service state, not tenant data.
      const response = await request(app.getHttpServer()).get('/api/health').expect(200);

      expect(response.body).toMatchObject({ status: 'ok' });
      expect(response.body.overallScore).toBeUndefined();
    });
  });
});
